services:

  traefik:
    image: traefik:v3.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - qstat-network

  client:
    build:
      context: ./Client
    container_name: qstat-client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api.localhost
    depends_on:
      - backend
    labels:
      - "traefik.http.routers.client.rule=Host(`app.${HOSTNAME}`)"
    networks:
      - qstat-network


  backend:
    build:
      context: ./Backend
    container_name: qstat-api
    ports:
      - "8000:8000"
    environment:
      - VLLM_BASE_URL=http://vllm:8000/v1
#      - DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PWD}@postgresql:5432/${PG_DB}
      - CUDA_VISIBLE_DEVICES=0
      - CHROMA_URL=http://chroma:8000
    labels:
      - "traefik.http.routers.backend.rule=Host(`api.${HOSTNAME}`)"
    depends_on:
 #     postgresql: 
 #       condition: service_healthy
      vllm: 
        condition: service_started
      chroma:
        condition: service_started    
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/whisper:/root/.cache/whisper
      - ~/.cache/chroma:/root/.cache/chroma
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - qstat-network


  chroma:
    image: chromadb/chroma
    volumes:
      - chroma-data:/data
    networks:
      - qstat-network


  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    ports:
      - "8001:8000"
    command: >
      --model Qwen/Qwen3-14B-AWQ
      --max-model-len 4096
      --gpu-memory-utilization 0.85
      --host 0.0.0.0
      --port 8000
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - qstat-network

# Postgres not in use for now, will be added back later
#  postgresql:
#    image: pgvector/pgvector:0.8.2-pg18-bookworm
#    container_name: postgres_qstat
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: ${PG_DB}
#      POSTGRES_USER: ${PG_USER}
#      POSTGRES_PASSWORD: ${PG_PWD}
#    volumes:
#      - postgres-data:/var/lib/postgresql/18/data
#      - ./Docker/postgres/init:/docker-entrypoint-initdb.d:ro
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - qstat-network


volumes:
  chroma-data:
#  postgres-data:

    


networks:
  qstat-network:
    driver: bridge