services:

  traefik:
    image: traefik:v3.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - qstat-network

  frontend:
    build:
      context: ./Frontend
    container_name: qstat-client
    ports:
      - "3000:3000"
    environment:
      - FASTAPI_URL=http://backend:8000
      - ORIGIN=http://app.${HOSTNAME}
      - BODY_SIZE_LIMIT=Infinity
    depends_on:
      - backend
    labels:
      - "traefik.http.routers.client.rule=Host(`app.${HOSTNAME}`)"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
    networks:
      - qstat-network


  backend:
    build:
      context: ./Backend
    container_name: qstat-api
    ports:
      - "8000:8000"
    environment:
      - VLLM_BASE_URL=http://vllm:8000/v1
      - CUDA_VISIBLE_DEVICES=0
      - CHROMA_URL=http://chroma:8000
      - OPENROUTER_KEY=${OPENROUTER_KEY}
    labels:
      - "traefik.http.routers.backend.rule=Host(`api.${HOSTNAME}`)"
    depends_on:
      vllm: 
        condition: service_started
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/whisper:/root/.cache/whisper
      - ~/.cache/chroma:/root/.cache/chroma
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - qstat-network


  vllm:
    image: vllm/vllm-openai:v0.24.0
    container_name: vllm
    ports:
      - "8001:8000"
    command: >
      --model ${MODEL_NAME}
      --quantization awq 
      --dtype half 
      --max-model-len ${CONTEXT_WINDOW_LEN} 
      --gpu-memory-utilization 0.85 
      --host 0.0.0.0 
      --port 8000
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - VLLM_WSL2_ENABLE_PIN_MEMORY=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - qstat-network


networks:
  qstat-network:
    driver: bridge