services:

  traefik:
    image: traefik:v3.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - qstat-network

  client:
    build:
      context: ./Client
    container_name: qstat-client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api.localhost
    depends_on:
      - backend
    labels:
      - "traefik.http.routers.client.rule=Host(`app.${HOSTNAME}`)"
    networks:
      - qstat-network


  backend:
    build:
      context: ./Backend
    container_name: qstat-api
    ports:
      - "8000:8000"
    environment:
      - VLLM_BASE_URL=http://vllm:8000/v1
      - CUDA_VISIBLE_DEVICES=0
    labels:
      - "traefik.http.routers.backend.rule=Host(`api.${HOSTNAME}`)"
    depends_on:
      - vllm
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/whisper:/root/.cache/whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - qstat-network


  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    ports:
      - "8001:8000"
    command: >
      --model Qwen/Qwen3-14B-AWQ
      --max-model-len 4096
      --gpu-memory-utilization 0.85
      --host 0.0.0.0
      --port 8000
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - qstat-network



networks:
  qstat-network:
    driver: bridge